import { TbChartBar, TbBook, TbCheck, TbChevronLeft, TbChevronRight, TbCloudCheck, TbCopy, TbFocus2, TbDownload, TbFilePlus, TbFileDescription, TbFolderOpen, TbEdit, TbPlus, TbRoute, TbDeviceFloppy, TbAdjustmentsHorizontal, TbShieldCheck, TbRestore, TbSearch, TbArrowRight, TbTrash, TbAlertTriangle, TbArrowBackUp, TbArrowForwardUp, TbUpload, TbX, TbChartLine, TbShieldExclamation } from 'react-icons/tb';
import { PiChartBar, PiBookOpen, PiCheck, PiCaretLeft, PiCaretRight, PiCloudCheck, PiCopy, PiCrosshair, PiDownloadSimple, PiFilePlus, PiFileText, PiFolderOpen, PiPencilSimpleLine, PiPlus, PiPath, PiFloppyDisk, PiSlidersHorizontal, PiShieldCheck, PiClockCounterClockwise, PiMagnifyingGlass, PiArrowRight, PiTrash, PiWarning, PiArrowUUpLeft, PiArrowUUpRight, PiUploadSimple, PiX, PiChartLine, PiShieldWarning } from 'react-icons/pi';
import { PiChartBarDuotone, PiBookOpenDuotone, PiCheckDuotone, PiCaretLeftDuotone, PiCaretRightDuotone, PiCloudCheckDuotone, PiCopyDuotone, PiCrosshairDuotone, PiDownloadSimpleDuotone, PiFilePlusDuotone, PiFileTextDuotone, PiFolderOpenDuotone, PiPencilSimpleLineDuotone, PiPlusDuotone, PiPathDuotone, PiFloppyDiskDuotone, PiSlidersHorizontalDuotone, PiShieldCheckDuotone, PiClockCounterClockwiseDuotone, PiMagnifyingGlassDuotone, PiArrowRightDuotone, PiTrashDuotone, PiWarningDuotone, PiArrowUUpLeftDuotone, PiArrowUUpRightDuotone, PiUploadSimpleDuotone, PiXDuotone, PiChartLineDuotone, PiShieldWarningDuotone } from 'react-icons/pi';
import { HiChartBar, HiBookOpen, HiCheck, HiChevronLeft, HiChevronRight, HiCheckBadge, HiDocumentDuplicate, HiViewfinderCircle, HiArrowDownTray, HiDocumentPlus, HiDocumentText, HiFolderOpen, HiPencilSquare, HiPlus, HiMap, HiArchiveBoxArrowDown, HiAdjustmentsHorizontal, HiShieldCheck, HiArrowPath, HiMagnifyingGlass, HiArrowRight, HiTrash, HiExclamationTriangle, HiArrowUturnLeft, HiArrowUturnRight, HiArrowUpTray, HiXMark, HiPresentationChartLine, HiExclamationCircle } from 'react-icons/hi2';
import { RiBarChartBoxLine, RiBookOpenLine, RiCheckLine, RiArrowLeftSLine, RiArrowRightSLine, RiCheckboxCircleLine, RiFileCopyLine, RiFocus3Line, RiDownload2Line, RiFileAddLine, RiFileTextLine, RiFolderOpenLine, RiEditLine, RiAddLine, RiRouteLine, RiSave3Line, RiEqualizerLine, RiShieldCheckLine, RiHistoryLine, RiSearchLine, RiArrowRightLine, RiDeleteBin6Line, RiErrorWarningLine, RiArrowGoBackLine, RiArrowGoForwardLine, RiUpload2Line, RiCloseLine, RiLineChartLine, RiShieldFlashLine } from 'react-icons/ri';

export const ICON_MAPS = {
  technical: { BarChart2: TbChartBar, BookOpen: TbBook, Check: TbCheck, ChevronLeft: TbChevronLeft, ChevronRight: TbChevronRight, CloudCheck: TbCloudCheck, Copy: TbCopy, Crosshair: TbFocus2, Download: TbDownload, FilePlus2: TbFilePlus, FileText: TbFileDescription, FolderOpen: TbFolderOpen, PencilLine: TbEdit, Plus: TbPlus, Route: TbRoute, Save: TbDeviceFloppy, Settings2: TbAdjustmentsHorizontal, ShieldCheck: TbShieldCheck, ArchiveRestore: TbRestore, Search: TbSearch, ArrowRight: TbArrowRight, Trash2: TbTrash, TriangleAlert: TbAlertTriangle, Undo2: TbArrowBackUp, Redo2: TbArrowForwardUp, Upload: TbUpload, X: TbX, Activity: TbChartLine, ShieldAlert: TbShieldExclamation },
  rounded: { BarChart2: PiChartBar, BookOpen: PiBookOpen, Check: PiCheck, ChevronLeft: PiCaretLeft, ChevronRight: PiCaretRight, CloudCheck: PiCloudCheck, Copy: PiCopy, Crosshair: PiCrosshair, Download: PiDownloadSimple, FilePlus2: PiFilePlus, FileText: PiFileText, FolderOpen: PiFolderOpen, PencilLine: PiPencilSimpleLine, Plus: PiPlus, Route: PiPath, Save: PiFloppyDisk, Settings2: PiSlidersHorizontal, ShieldCheck: PiShieldCheck, ArchiveRestore: PiClockCounterClockwise, Search: PiMagnifyingGlass, ArrowRight: PiArrowRight, Trash2: PiTrash, TriangleAlert: PiWarning, Undo2: PiArrowUUpLeft, Redo2: PiArrowUUpRight, Upload: PiUploadSimple, X: PiX, Activity: PiChartLine, ShieldAlert: PiShieldWarning },
  duotone: { BarChart2: PiChartBarDuotone, BookOpen: PiBookOpenDuotone, Check: PiCheckDuotone, ChevronLeft: PiCaretLeftDuotone, ChevronRight: PiCaretRightDuotone, CloudCheck: PiCloudCheckDuotone, Copy: PiCopyDuotone, Crosshair: PiCrosshairDuotone, Download: PiDownloadSimpleDuotone, FilePlus2: PiFilePlusDuotone, FileText: PiFileTextDuotone, FolderOpen: PiFolderOpenDuotone, PencilLine: PiPencilSimpleLineDuotone, Plus: PiPlusDuotone, Route: PiPathDuotone, Save: PiFloppyDiskDuotone, Settings2: PiSlidersHorizontalDuotone, ShieldCheck: PiShieldCheckDuotone, ArchiveRestore: PiClockCounterClockwiseDuotone, Search: PiMagnifyingGlassDuotone, ArrowRight: PiArrowRightDuotone, Trash2: PiTrashDuotone, TriangleAlert: PiWarningDuotone, Undo2: PiArrowUUpLeftDuotone, Redo2: PiArrowUUpRightDuotone, Upload: PiUploadSimpleDuotone, X: PiXDuotone, Activity: PiChartLineDuotone, ShieldAlert: PiShieldWarningDuotone },
  solid: { BarChart2: HiChartBar, BookOpen: HiBookOpen, Check: HiCheck, ChevronLeft: HiChevronLeft, ChevronRight: HiChevronRight, CloudCheck: HiCheckBadge, Copy: HiDocumentDuplicate, Crosshair: HiViewfinderCircle, Download: HiArrowDownTray, FilePlus2: HiDocumentPlus, FileText: HiDocumentText, FolderOpen: HiFolderOpen, PencilLine: HiPencilSquare, Plus: HiPlus, Route: HiMap, Save: HiArchiveBoxArrowDown, Settings2: HiAdjustmentsHorizontal, ShieldCheck: HiShieldCheck, ArchiveRestore: HiArrowPath, Search: HiMagnifyingGlass, ArrowRight: HiArrowRight, Trash2: HiTrash, TriangleAlert: HiExclamationTriangle, Undo2: HiArrowUturnLeft, Redo2: HiArrowUturnRight, Upload: HiArrowUpTray, X: HiXMark, Activity: HiPresentationChartLine, ShieldAlert: HiExclamationCircle },
  compact: { BarChart2: RiBarChartBoxLine, BookOpen: RiBookOpenLine, Check: RiCheckLine, ChevronLeft: RiArrowLeftSLine, ChevronRight: RiArrowRightSLine, CloudCheck: RiCheckboxCircleLine, Copy: RiFileCopyLine, Crosshair: RiFocus3Line, Download: RiDownload2Line, FilePlus2: RiFileAddLine, FileText: RiFileTextLine, FolderOpen: RiFolderOpenLine, PencilLine: RiEditLine, Plus: RiAddLine, Route: RiRouteLine, Save: RiSave3Line, Settings2: RiEqualizerLine, ShieldCheck: RiShieldCheckLine, ArchiveRestore: RiHistoryLine, Search: RiSearchLine, ArrowRight: RiArrowRightLine, Trash2: RiDeleteBin6Line, TriangleAlert: RiErrorWarningLine, Undo2: RiArrowGoBackLine, Redo2: RiArrowGoForwardLine, Upload: RiUpload2Line, X: RiCloseLine, Activity: RiLineChartLine, ShieldAlert: RiShieldFlashLine },
};
